axis_linear: 1
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 0
scale_angular: 0.4

axis_arm_joint3: 2
scale_arm_joint3: 0.3

axis_arm_joint4: 3
scale_arm_joint4: 0.3

enable_button: 5  # L2 shoulder button
enable_turbo_button: 10  # L1 shoulder button
