axis_linear: 4
scale_linear: 0.6
scale_linear_turbo: 0.8

axis_angular: 3
scale_angular: 0.8

axis_arm_joint3: 1
scale_arm_joint3: 0.3

axis_arm_joint4: 0
scale_arm_joint4: 0.3

button_flipper_front_dn: 2
button_flipper_front_up: 3
button_flipper_rear_dn: 0
button_flipper_rear_up: 1
scale_flipper_rear: 0.5
scale_flipper_front: 0.5

enable_button: 5  # R1 shoulder button
enable_turbo_button: 4  # L1 shoulder button
