axis_linear: 4
scale_linear: 0.4
scale_linear_turbo: 0.8

axis_angular: 3
scale_angular: 1.0

axis_flipper: 1
scale_flipper: 0.6

enable_button: 5  # L2 shoulder button
enable_turbo_button: 4  # L1 shoulder button
